import Layout from "@/layouts/Layout";
import Head from "next/head";
import React from "react";
import { InventoryContextProvider } from "@/context/inventoryContext";

const app = () => (
  <>
    <Head>
      <title>Inventory</title>
      <meta name="description" content="Generated by create next app" />
      <meta name="viewport" content="width=device-width, initial-scale=1" />
      <link rel="icon" href="/favicon.ico" />
    </Head>
    <Layout>
      <InventoryContextProvider></InventoryContextProvider>
    </Layout>
  </>
);

export default app;
