import React, { useEffect, useState } from "react";
import { Material } from "@prisma/client";
import { Column } from "@/utils/utils";
import Layout from "@/layouts/Layout";
import { useNavigationContext } from "@/context/NavigationContext";
import {
  InventoryContextProvider,
  useInventoryContext,
} from "@/context/InventoryContext";
import { NextPage } from "next";
import Head from "next/head";
import { FormDialogAddMovement } from "@/components/dialog/FormDialogAddMovement";
import TableReactDataGrid from "@/components/TableReactDataGrid";
import PrivateRoute from "@/components/PrivateRoute";

const InventoryPage: NextPage = () => (
  <PrivateRoute>
    <Head>
      <title>Create Next App</title>
      <meta name="description" content="Generated by create next app" />
      <meta name="viewport" content="width=device-width, initial-scale=1" />
      <link rel="icon" href="/favicon.ico" />
    </Head>
    <Layout>
      <InventoryContextProvider>
        <div className="flex flex-col h-full w-full">
          <InventoryManagement />
        </div>
      </InventoryContextProvider>
    </Layout>
  </PrivateRoute>
);

const InventoryManagement = () => {
  const [materialSelected, setMaterialSelected] = useState<number>(0);
  const { setTituloHeader } = useNavigationContext();

  useEffect(() => {
    setTituloHeader("Gestión de inventarios");
  }, []);

  return (
    <div className="flex w-full flex-col h-full px-5">
      <div className="flex justify-between">
        <InputSearchMovement
          materialSelected={materialSelected}
          setMaterialSelected={setMaterialSelected}
        />
        <ButtonAddMovement />
      </div>
      <InventoryTable2 materialSelected={materialSelected}></InventoryTable2>

      <FormDialogAddMovement />
    </div>
  );
};

const InventoryTable2 = ({ materialSelected }: any) => {
  // TODO Servico para consultar los movimientos, el servicio debe retornar la lista de movimientos con filtro.
  // TODO usar [materialSelected] para el filtro
  // TODO Tambien el calculo de la cantidad disponible.
  // TODO organizar el objeto response de la forma de [datos]

  const [dataSource, setDataSource] = useState<any>([]);
  const [cantidadDisponible] = useState<number>(35);
  const [loading, setLoading] = useState(true);

  useEffect(() => {
    if (materialSelected) {
      const datos = new Promise((resolve) => {
        setTimeout(() => {
          const testData = Array.from({ length: 200 }, (_, index) => ({
            id: index + 1,
            quantity: index * 3,
            creation_date: new Date(),
            material_id: (index + 2) * 100,
            movement_type: index % 2 == 0 ? "ENTRADA" : "SALIDA",
          }));

          const updatedDataSource: any = testData.map((dato) => ({
            ...dato,
            creation_date: dato.creation_date.toLocaleDateString(),
          }));

          updatedDataSource.forEach((dato: any) => {
            if (dato.movement_type === "ENTRADA") {
              dato.entradas = dato.quantity;
            }
            if (dato.movement_type === "SALIDA") {
              dato.salidas = dato.quantity;
            }
          });
          resolve(updatedDataSource);
        }, 1500);
      });

      setLoading(false);
      setDataSource(datos);
    } else {
      setLoading(true);
    }
  }, [materialSelected]);
  if (loading) return <div>Selecciona un material</div>;

  const columns: Column[] = [];
  columns.push({ name: "id", header: "Identificador" });
  columns.push({ name: "creation_date", header: "Fecha del movimiento" });
  columns.push({ name: "entradas", header: "Entradas" });
  columns.push({ name: "salidas", header: "Salidas" });

  return (
    <>
      <TableReactDataGrid dataSource={dataSource} columns={columns} />
      <div className="flex justify-end pr-0 mt-5 text-lg mb-24">
        Cantidad disponible: {cantidadDisponible}
      </div>
    </>
  );
};

const ButtonAddMovement = () => {
  const { setOpenDialogMovements } = useInventoryContext();

  return (
    <div className="flex my-5 justify-end">
      <button type="button" onClick={() => setOpenDialogMovements(true)}>
        Agregar movimiento
      </button>
    </div>
  );
};

const InputSearchMovement = ({
  materialSelected,
  setMaterialSelected,
}: {
  materialSelected: number;
  setMaterialSelected: React.Dispatch<React.SetStateAction<number>>;
}) => {
  // TODO Servico para consultar los materiales
  // TODO organizar el objeto response de la forma de [materiales]

  const handleMaterialChange = (
    event: React.ChangeEvent<HTMLSelectElement>
  ) => {
    setMaterialSelected(parseInt(event.target.value, 10));
  };

  let materiales: Material[] = [
    {
      id: 1,
      name: "material1",
      available: 1,
      creation_date: new Date(),
      user_id: 1,
    },
    {
      id: 2,
      name: "material2",
      available: 1,
      creation_date: new Date(),
      user_id: 1,
    },
  ];

  if (materiales && materiales.length > 0) {
    setMaterialSelected(parseInt(String(materiales[0].id), 10));
  }

  return (
    <div className="flex my-5">
      <select
        required
        value={materialSelected}
        name="material"
        onChange={handleMaterialChange}
      >
        {materiales?.map((material) => (
          <option key={`material_${material.id}`} value={material.id}>
            {material.name}
          </option>
        ))}
      </select>
    </div>
  );
};
export default InventoryPage;
